#!/usr/bin/env bash
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

export RUN_PROSODY_FEATURES="${RUN_PROSODY_FEATURES:-1}"
export DATASET_NAME="${DATASET_NAME:-zh45w_en22w_no_text}"
export N_VQ="${N_VQ:-32}"
export SKIP_EXISTING="${SKIP_EXISTING:-1}"
export FORCE="${FORCE:-0}"
export TRAIN_VERSION="${TRAIN_VERSION:-ver2}"

export GPU_IDS="${GPU_IDS:-0,1,2,3,4,5,6,7}"
export CODEC_SHARD_COUNT="${CODEC_SHARD_COUNT:-8}"
export SPEAKER_SHARD_COUNT="${SPEAKER_SHARD_COUNT:-8}"
export PROSODY_SHARD_COUNT="${PROSODY_SHARD_COUNT:-16}"
export CODEC_DEVICE="${CODEC_DEVICE:-cuda:0}"
export SPEAKER_DEVICE="${SPEAKER_DEVICE:-cuda:0}"

export TRAIN_TARGET_SPK_WEIGHT="${TRAIN_TARGET_SPK_WEIGHT:-0.05}"
export TRAIN_SOURCE_SUPPRESS_WEIGHT="${TRAIN_SOURCE_SUPPRESS_WEIGHT:-0.05}"
export TRAIN_SPEAKER_MARGIN="${TRAIN_SPEAKER_MARGIN:-0.1}"
export TRAIN_LAMBDA_ROUTE="${TRAIN_LAMBDA_ROUTE:-0.01}"
export TRAIN_LAMBDA_PROSODY="${TRAIN_LAMBDA_PROSODY:-0.05}"
export TRAIN_LAMBDA_CONTENT="${TRAIN_LAMBDA_CONTENT:-0.0}"
export TRAIN_PROSODY_F0_WEIGHT="${TRAIN_PROSODY_F0_WEIGHT:-0.0}"
export TRAIN_PROSODY_VOICED_WEIGHT="${TRAIN_PROSODY_VOICED_WEIGHT:-0.0}"
export TRAIN_PROSODY_ENERGY_WEIGHT="${TRAIN_PROSODY_ENERGY_WEIGHT:-0.5}"
export TRAIN_PROSODY_PAUSE_WEIGHT="${TRAIN_PROSODY_PAUSE_WEIGHT:-1.0}"
export TRAIN_PROSODY_DURATION_WEIGHT="${TRAIN_PROSODY_DURATION_WEIGHT:-0.5}"

bash scripts/001014_build_train_ready_no_text.sh "$@"
